import './fonts/BwModelicaCyrillicDEMO-Medium.woff'
import './fonts/BwModelicaCyrillicDEMO-Medium.woff2'
import './fonts/BwModelicaCyrillicDEMO-Bold.woff'
import './fonts/BwModelicaCyrillicDEMO-Bold.woff2'

import './images/bank01.svg'
import './images/bank01-sm.svg'
import './images/bank02.svg'
import './images/bank02-sm.svg'
import './images/bank03.svg'
import './images/bank03-sm.svg'
import './images/bank04.svg'
import './images/bank04-sm.svg'
import './images/bank05.svg'
import './images/bank05-sm.svg'
import './images/bank06.svg'
import './images/bank06-sm.svg'
import './images/bank07.svg'
import './images/bank07-sm.svg'
import './images/bank08.svg'
import './images/bank08-sm.svg'
import './images/bank09.svg'
import './images/bank09-sm.svg'

import 'normalize.css/normalize.css'
import 'ion-rangeslider/css/ion.rangeSlider.min.css'
import './index.scss'

import './scripts/script.js'
